### ISSUE TITLE
TEMPLATE: Footer

### ISSUE THREAD

**Issue by Blaize-Egelhof** [Blaize-Egelhof/P4-Genepool#32]

**Comment by zablon-oigo** [comment]
hello, how would you like the footer to be designed?

**Comment by Blaize-Egelhof** [comment]
> hello, how would you like the footer to be designed?

Hi Zablon , many thanks for kindly offered assistance, unfortunately I am going to have to decline as this project needs to be solely designed and coded by me as a student project for my institute . 

Regards,
